### ISSUE TITLE
host.update fails when assigning a template to a host that already has that template

### ISSUE THREAD

**Issue by msims-okta** [express42/zabbixapi#4]
Wondering if host.update could just warn and skip over if a template is already assigned to the host, rather than just fail hard.

``` ruby
/usr/local/share/gems1.9/gems/zabbixapi-0.6.4/lib/zabbixapi/client.rb:85:in `_request': Server answer API error: (RuntimeError)
 {
  "code": -32602,
  "message": "Invalid params.",
  "data": "Interface is linked to item \"Zabbix:agent:ping\" on \"host-test\"."
}
 on request:
 {
  "method": "host.update",
  "params": {
    "host": "host-test",
    "hostid": 10851,
    "status": 1,
    "interfaces": [
      {
        "type": 1,
        "main": 1,
        "useip": 0,
        "ip": "0.0.0.0",
        "dns": "host-test",
        "port": "10050"
      }
    ],
    "groups": [
      {
        "groupid": 2
      },
      {
        "groupid": 34
      },
      {
        "groupid": 10
      }
    ],
    "templates": [
      {
        "templateid": 10228
      },
      {
        "templateid": 10001
      },
      {
        "templateid": 10287
      }
    ]
  },
  "auth": "57510d7f92fc1ccb60bc1eaad4735e5f",
  "id": 27796,
  "jsonrpc": "2.0"
}
    from /usr/local/share/gems1.9/gems/zabbixapi-0.6.4/lib/zabbixapi/client.rb:90:in `api_request'
    from /usr/local/share/gems1.9/gems/zabbixapi-0.6.4/lib/zabbixapi.rb:18:in `query'
    from ./zabbix-update-host:50:in `<main>'
```

**Comment by dmitry-wht** [comment]
It will fail because Zabbix is trying to delete-add interface. And it can't delete interface while you have items which are using it. See https://www.zabbix.com/documentation/3.0/manual/api/reference/host/update
> interfaces  object/array  Host interfaces to replace the current host interfaces.  

Possible workaround to use Host interface method
```ruby
hostid = zbx.hosts.get_id(:host => 'host_name')
unless hostid.nil?
  # Update everything except interface
  zbx.hosts.update(
    :hostid => hostid,
    :groups => some_group_id,
    :status => 0_or_1 # 0 - Enable; 1 - Disable
  )
  # Get interface id (main => 1 for default, type => 1 for zabbix agent. 
  # For other intreface see https://www.zabbix.com/documentation/3.0/manual/api/reference/hostinterface/object)
  interface_id = zbx.query(
    :method => "hostinterface.get",
    :params => {
      :output => "interfaceid",
      :hostids => hostid,
      :filter => {:main => 1, :type => 1}
  }).first["interfaceid"]
  # Update zabbix host interface
  zbx.query(
    :method => "hostinterface.update",
    :params => {
    :interfaceid => interface_id,
    :ip => '127.0.0.1',
    :dns => 'localhost',
    :port => 10050,
    :useip => 0_or_1 # 0 - use DNS name ; 1 - use IP address 
  })
else
  # Create zabbix host
  zbx.hosts.create(
    :host => 'host_name',
    :name => 'visible_name',
    :interfaces => [
      {
        :type => 1,
        :main => 1,
        :ip => '127.0.0.1',
        :dns => 'localhost',
        :port => 10050,
        :useip => 0_or_1 # 0 - use DNS name ; 1 - use IP address 
      }
    ],
    :groups => some_group_id,
    :status => 0_or_1 # 0 - Enable; 1 - Disable
  )
end
```

**Comment by fmotnaldo** [comment]
I got a similar error when I tried to add a new host this error occur. 

Template cannot be linked to another template more than once even through other templates.

I really don't know what to do. Please I need help.

Regardds

**Comment by evtuhovich** [comment]
@fmotnaldo there is a comment previous to yours, where you can find workaround.

This is not zabbixapi gem problem, it's inside zabbix logic, and i don't know how i can fix this :-(

**Comment by fmotnaldo** [comment]
please tell me the topic so Ic an search it. Is the commmen for msims-okta?. I really don't know who to run that sintaxt. I need to create a new .php under /usr/share/zabbix/include/classes/api/services/CHost.php. After that restart the zabbix server?.

**Comment by evtuhovich** [comment]
I am telling about @dmitry-wht answer

**Comment by UlyssesAlves** [comment]
Not the most beautiful solution, but maybe you could try to ignore the property "hosts" so that Zabbix API igores it on the update, or you could remove the links and then add them again. Of course you won't have any transaction scope in this situation, but at least (if it works) you pass by this limitation of theirs.
