### ISSUE TITLE
usergroup.massadd is deprecated in 4.x and should be replaced by usergroup.update

### ISSUE THREAD

**Issue by testaccountje** [express42/zabbixapi#94]
After updating our Zabbix servers to version 4.0.5 I'm experiencing this error:
 
```
/usr/local/rvm/gems/ruby-2.3.1/gems/zabbixapi-4.1.0/lib/zabbixapi/client.rb:127:in `_request': Server answer API error (ZabbixApi::ApiError)
 {
  "code": -32602,
  "message": "Invalid params.",
  "data": "Incorrect method \"usergroup.massAdd\"."
}
 on request:
 {
  "method": "usergroup.massAdd",
  "params": {
    "usrgrpids": [
      54
    ],
    "rights": [
      {
        "permission": 2,
        "id": "1"
      },
   ..
      {
        "permission": 2,
        "id": "197"
      }
    ]
  },
  "id": 10757,
  "jsonrpc": "2.0",
  "auth": “xxx”
}
from /usr/local/rvm/gems/ruby-2.3.1/gems/zabbixapi-4.1.0/lib/zabbixapi/client.rb:145:in `api_request'
from /usr/local/rvm/gems/ruby-2.3.1/gems/zabbixapi-4.1.0/lib/zabbixapi/classes/usergroups.rb:32:in `set_perms'
```
which is a result of the deprecation of 'usergroup.massadd, usergroup.massupdate' among others. see:
- https://www.zabbix.com/documentation/4.0/manual/api/changes_3.4_-_4.0
- https://support.zabbix.com/browse/ZBXNEXT-4247

**Comment by Splyth** [comment]
I think the solution in this case is to bump our supported versions, remove these functions
and run our tests to make sure everything is kosher.

Any objections?

 @snehitgajjar

**Comment by anapsix** [comment]
afaik, the issue is no longer relevant
